spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:

        # USER-SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /addresses/**

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**, /categories/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
