spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:

        # USER-SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/us/**

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/ps/**

        # ORDER-SERVICE
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/os/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
