spring:
  # DATASOURCE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db?createDatabaseIfNotExist=true
    username: root
    password: pandU@420
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  app:
    base-url: /api/v1/os
    client:
      product:
        name: product-service
        url: http://localhost:7002/api/v1/ps